// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import { TurboModalController, LimitVisibleController } from "dm_unibo_common"
application.register("turbo-modal", TurboModalController)
application.register("limit-visible", LimitVisibleController)
